name: Add publications by author ID ✔️
description:  |
  Paste the Semantic Scholar ID of an author to add all their publications within a time frame.
title: "[Add publications by an author]"
labels: ["automatic-add-publications-by-author"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        This will add all publications by the author within the specified time frame using the Semantic Scholar API. To do this, a Semantic Scholar author ID is needed, which can be found by searching for the author in Semantic Scholar.
        
        Notes: 
          - Since the API can only find the year of a publication, the month and day will be automatically set to January 1st.
          - If you wish to be correctly attributed as the author, please add your Semantic Scholar ID to your member profile. To do this, fill the [issue form to update your member profile](/issues/new/choose).

        This form will automatically generate a PR that will be reviewed by the maintainers.
# AB,VWA,WA,Work,Work++
  - type: input
    id: judge_name
    attributes:
      label: Judge Model Name
      description: Enter the name of your judge model. This is what will be displayed on the leaderboard.
    validations:
      required: true
  
  - type: input
    id: author
    attributes:
      label: Author
      description: Enter the name of the author of the judge model. This is what will be displayed on the leaderboard. It can either be an author name (e.g. "John Doe et al."), a GitHub username (e.g. "octocat"), a research group name (e.g. "Agents @ McGill-NLP").

  - type: input
    id: link
    attributes:
      label: Link
      description: Enter the link to the paper or the GitHub repository of the judge model. This is what will be displayed on the leaderboard.
  
  - type: input
    id: overall
    attributes:
      label: Overall
      description: Report your overall precision score (numerical between 0 and 1).
      placeholder: "0.0"
    validations:
      required: true
    
  - type: input
    id: AssistantBench
    attributes:
      label: assistantbench
      description: Report your precision score (numerical between 0 and 1) for AssistantBench.
      placeholder: "0.0"
    validations:
      required: true
  
  - type: input
    id: VisualWebArena
    attributes:
      label: visualwebarena
      description: Report your precision score (numerical between 0 and 1) for VisualWebArena.
      placeholder: "0.0"
    validations:
      required: true

  - type: input
    id: WebArena
    attributes:
      label: webarena
      description: Report your precision score (numerical between 0 and 1) for WebArena.
      placeholder: "0.0"
    validations:
      required: true
  
  - type: input
    id: WorkArena
    attributes:
      label: workarena
      description: Report your precision score (numerical between 0 and 1) for WorkArena.
      placeholder: "0.0"
    validations:
      required: true
  
  - type: input
    id: WorkArena++
    attributes:
      label: workarena++
      description: Report your precision score (numerical between 0 and 1) for WorkArena++.
      placeholder: "0.0"
    validations:
      required: true